### PR TITLE
Implementing "lets" as syntactic sugar

### PR DESCRIPTION
**Pull request by Gaspi**
This is related to Issue #101

### CODE REVIEW

**Comment by Gaspi** [comment]
Travis seems broken on switching opam to ocaml4.04.2 right now (and since opam2.0)...
BTW, if you have any clue how to fix it, feel free to PR.

**Comment by rlepigre** [comment]
Is it really a good idea to extend the syntax right now? I don't really want to spend my time updating the backward compatibility of the `lambdapi` legacy parser.

**Comment by fblanqui** [comment]
Yes, what's the point in adding new features to Dedukti if we move to 
Lambdapi soon?

Le 18/10/2018 à 10:39, Rodolphe Lepigre a écrit :

**Comment by Gbury** [comment]
@rlepigre well, what's your idea of unreasonable size ? Archsat will happily generate text files of at least a few Mb (and up to a few Gb), containing at least undreds, and often ten of thousands of sequential let-bindings.

Also, is lambdapi released on opam (and by that I mean the official opam repository) ?

**Comment by Gaspi** [comment]
@Gbury mentionned yesterday the need for a tiny syntactic sugar to efficiently translate proofs from Archsat to (old syntax) Dedukti. Is it difficult to apply the exact same parser modification on the legacy parser in lambdapi, @rlepigre ?

**Comment by fblanqui** [comment]
@Gbury <https://github.com/Gbury>, why not generating Lambdapi files? 
There's already a "let" in Lambdapi.


Le 18/10/2018 à 10:52, Gaspard Férey a écrit :

**Comment by rlepigre** [comment]
@Gbury I don't have a precise answer because this should be benched, but I guess unreasonable means something like "more than twenty megabytes". That being said, it may well be that the new syntax is parsed a lot more efficiently than the old one.

The latest version of `lambdapi` without the new syntax is not on (official) `opam` yet, only the previous one is. However, a new release should be published soon.

@gaspi No it is not difficult, but I'd rather not have to do it.

**Comment by GuillaumeGen** [comment]
The syntax seems reasonable to me, but I do think that a change of syntax require new tests.
@rlepigre I agree with you, there is no reason that **you** modify the legacy parser. So I suppose this PR should come with one on lambdapi too. (I will do it)

**Comment by Gbury** [comment]
So I just tried lambdapi, but couldn't get it to work with separate modules (the dedukti `-I` option seems to be absent in any form...), which brings me to the following point: lambdapi seems to suffer from the same kind of lack of documentation that plagues dedukti: no manpages, no explanation of separate compilation (that's the information that would typically be found in manpages), and neither the syntax nor the main differences with dedukti appear to be documented online (or at least, they aren't linked from the README).

So, let me re-iterate one more time: I don't know if that's a conscious choice but currently, both dedukti and lambdapi lack documentation (i.e. **accessible** documentation) to a point where serious development by people who aren't in deducteam (or closely related), is extremely annoying, or even borderline impossible without directly contacting deducteam. 

Finally, note that it would ne nice if the lambdapi repo was in the deducteam organization if it is the successor of dedukti (side note: why change the name, and not just call it dedukti v3 ?).

**Comment by fblanqui** [comment]
Hi Guillaume.

Thanks for your mail!

Le 18/10/2018 à 11:38, Guillaume Bury a écrit :
>
> So I just tried lambdapi, but couldn't get it to work with separate 
> modules (the dedukti |-I| option seems to be absent in any form...), 
> which brings me to the following point: lambdapi seems to suffer from 
> the same kind of lack of documentation that plagues dedukti: no 
> manpages, no explanation of separate compilation (that's the 
> information that would typically be found in manpages), and neither 
> the syntax nor the main differences with dedukti appear to be 
> documented online (or at least, they aren't linked from the README).
>
> So, let me re-iterate one more time: I don't know if that's a 
> conscious choice but currently, both dedukti and lambdapi lack 
> documentation (i.e. *accessible* documentation) to a point where 
> serious development by people who aren't in deducteam (or closely 
> related), is extremely annoying, or even borderline impossible without 
> directly contacting deducteam.
>
Very good point! We should indeed provide a nice doc for newcomers. 
Could you please provide us with some nice example of doc (from your 
point of view) we could follow? What are the important elements we 
should put in this doc?


> Finally, note that it would ne nice if the lambdapi repo was in the 
> deducteam organization if it is the successor of dedukti (side note: 
> why change the name, and not just call it dedukti v3 ?).
>
Right. Rodolphe is going to move it to Deducteam next week.

As for the name, yes, Gilles wants to keep Dedukti. We should do that 
soon too. This implies to remove the .lp file extension.

Frédéric.

**Comment by Gbury** [comment]
As far as documentation goes, I would think the following would be good:
- manpages for all binaries installed by the dedukti project (related to #100 ). Each manpage should comport:
    + a few paragraphs to explain what dedukti is/does.
    + a detailed documentation of all options (more than the current few words for each option in the help)
    + (optionally) a few examples of dedkti usage

  Manpages could follow take inspiration from compilers manpages (dedukti is quite close to compilers), such as `ocamlc`.

- a complete formal description of the syntax (related to #102 ), e.g. in the BNF format, **with comments** to explain the purpose of each syntax construction. This is particularly required since, as I understand, dedukti is meant to be generated, in which case it is very important for the generators to know the lexical/syntaxic conventions. The tptp bnf syntax is a good example of such documentation: http://tptp.cs.miami.edu/~tptp/TPTP/SyntaxBNF.html
- maybe splitting the current README in order to have the sections starting from "A small example" in a separate file with a link to that file from the README. Similarly, links in the README to point to a tutorial, and the manual.
- write a separate manual, which explains dedukti in more depth (linking to papers explaining the lambda-pi modulo calculus), which explains how to use dedukti in depth, including examples of developements involving the various features of dedukti (such as separate compilation, confluence checking), and how to debug dedukti files (i.e. how to read/interpret error messages, and fix the affected file). The menhir user manual an excellent point of reference for good manuals I'd say.
- finally, probably a FAQ somewhere (possibly in the manual).

**Comment by rlepigre** [comment]
@GuillaumeGen OK, thank. But it could be a good idea to discuss this new syntax with everyone.

**Comment by rlepigre** [comment]
@Gbury thanks for the documentation ideas.

Note that the current version of `lambdapi` has not even be release yet. So documentation targeting potential external users has not been produced yet. However, there is already a file `syntax.bnf` at the root of the repository, giving the new syntax.

**Comment by GuillaumeGen** [comment]
> But it could be a good idea to discuss this new syntax with everyone.

It is of course intended, this is the reason why it is a PR.
However, @Gbury, who submits his thesis this week, seemed to need it in order to have a good generator of .dk in ArchSat, and it cost @Gaspi 3 lines of code, so it had been implemented before discussion.

**Comment by Gbury** [comment]
To be clear, it is not a hard requirement for my thesis. However, it would allow for far nicer proofs.

**Comment by rlepigre** [comment]
OK, I think we can merge then. Travis build should be fixed. However, it may be a good idea to add a couple of test files first.

**Comment by rlepigre** [comment]
@Gaspi: By the way, shouldn't the type annotation be optional?

**Comment by Gaspi** [comment]
I agree it would have been nice and my first try was indeed to allow for optional type annotation in "let"s. However, when inferring (or checking) an application, Dedukti always starts by **inferring** the type of the applied term and then **checks** that the arguments match the expected types.

Therefore any example of a "let" omitting the type annotation is an "applied unannotated lambda" which is rejected at typechecking. The typing algorithm could change in the future but I didn't see fit to allow a syntax that systematically fails at typechecking.

@GuillaumeGen I agree about the need for new tests. I'll add them to this PR.

@Gbury  Thanks a lot for the documentation advice !

**Pull request merged**
