### PR TITLE
Full implementation of AC(U) rewriting

### PR DESCRIPTION
**Pull request by Gaspi**
Many new features:
- Symbols now have an "algebra" in the signature describing how they behave. For now the possible algebra are : Free (no relation), AC or ACU. TODO: implement C (commutative) algebra.
- Introduction of a "printer" type to simplify notation  (type 'a printer = Format.formatter -> 'a -> unit)
- Removed symbol arity constraints in pattern matching (at the head and in nested occurences). Possibility to enforce these constraints back with a flag.
- Removed linearity constraints from non-left-linear rules. The decision tree now handles multiple occurences of the same variable in the patterns. Left-linearity is still detected and is still forbidden unless the -nl flag is provided.
- In pattern matching: no distinction between unapplied variables and "à la Miller" variables. Unapplied variables are simply "à la Miller" variables applied to an empty list of bounded variables. Corresponding matching problems are the same.
- Parser modifications to handle definition of AC(U) symbols using the "defac"/"defacu" operators.
- Implemented flattening / unflattening of AC-headed terms and sort of their arguments. This ensures that every term has a single SNF representation and allows for quick convertibility check using syntactical equality.
- Integrated AC to the decision tree algorithm: essentially added the possibility for the tree to non-deterministically "fetch" a [case]-headed term in the list of arguments of an AC symbol.
- Integrated AC to the matching. Represents most of the work (+400 lignes in matching.ml). All matching related functions should now be in the matching.ml file. The reduction algorithm uses successively the decision tree to deconstruct the term according to possible patterns and then relies on the matching to finalize and solve for the various variables of the problem. When no AC symbol are in the selected pattern this should reflect exactly the previous behavior (the reduction strategy is untouched). Although there is some limited impact on performance... TODO: measure this impact.
- Indentation, documentation and pretty printing here and there...
- Modification of the test script. This should actually be fairly consistent with the develop branch by now...
- A couple of new example files to show off and test the new AC(U) features.

### CODE REVIEW

**Comment by francoisthire** [comment]
Before I start reviewing the code, is there any performance issue?

**Comment by Gaspi** [comment]
Unnoticeable for the tests and simple examples. 15min instead of 10min for the type checking time of Matita. Performance is still a WIP (a couple of optimization I've thought of + I need to run the ocaml profiler to check for potential mistakes).

**Comment by GuillaumeGen** [comment]
Ce fichier est pour l'instant refusé :
```Nat : Type.

0 : Nat.
s : Nat -> Nat.

defac max [Nat].
[i, j]  max (s i) (s j) --> s (max i j).
[n]     max n n --> n.
[n,m]   max n (max n m) --> max n m.
[n]     max n (s n) --> s n.
[n,m]   max n (max (s n) m) --> max (s n) m.
[n,m]   max (s n) (max n m) --> max (s n) m.
[n]     max 0 n    --> n.

i : Nat.
j : Nat.

#CHECK max (s i) (s j) == max (s i) (max i (s j)).

**Comment by Gaspi** [comment]
This is very subtle but I think the behavior you point out is (at least close to) what's expected.
```
Nat : Type.
z : Nat.
s : Nat -> Nat.

defac max [Nat].
{rule1}  [n]          max (s n) n    -->     (s n)
{rule1'} [n,m]   max (max (s n) n) m --> max (s n) m
{rule2}  [n]     max z     n         --> n
{rule3}  [n,m]   max (s n) (s m)     --> s (max n m).
```

Your system is non confluent and the normal form computed for you left hand side is different from the normal form computed for the right hand side :
```
i : Nat.
j : Nat.
#EVAL[WHNF] max (s i) (max (s j) i).    (;   max i (s (max i j))  ;)
#EVAL[WHNF] max (s i) (s j).            (;   s (max i j)          ;)
```

The reason for this behavior can be investigated by printing the decision tree of `max`:
```
#GDT max.
```

- It is worth mentioning that when encountering an AC-headed rule of the shape
```max{T1 T2 ... Tn}   --> rhs```
where none of the `Ti` are pattern variables, AC matching silently adds an extra rule
```max{T1 T2 ... Tn X} --> max rhs X```
This allows our problematic term to match the `max (s n) (s m)` pattern which is expected in that case (even though the match is not strictly speaking "at the head of the term").

- Side note: whenever one of the `Ti` is already a variable, the extra rule is not added. This could be a problem when this variable is non-linear and may not match all remaining terms in a max-headed term like a fresh `X` would. I should probably change that.
This explains why `rule1`doesn't apply here and why `rule1'`is needed.

- In the given example, matching starts by trying to match `rule1` and fetches a `s`-headed in the AC-set {`s i`,`s j`,`i`}. In our case, `s j` is fetched (for some reason) and the matching proceeds. If it failed then `s i` will be picked later.

- Because of the (poor) first choice of `s`-headed term, both `rule1` and `rule1'` are not applicable.

- However, fetching `s i` as the second `s`-headed term make the "silent" version of `rule3` applicable.

The lesson here is that AC-matching is a mess...
I welcome any ideas for better design.

**Comment by fblanqui** [comment]
Yes, this system is not confluent. I would rather suggest to orient rule3 in the other way although it is not sufficient. You also need to add the infinite set of rules max(s^k(x),x) --> s^k(x) for every k>=0.

Gaspard, I do not understand how your algorithm works though. Why do you say that matching starts by trying to match rule1? Decision trees usually say which rule to apply depending on the shape of arguments. 

It also depends on the internal representation you use for applications of AC symbols. Do you use a new private term constructor AC:ac_symbol -> term list -> term with the invariant that no term argument is headed by the same ac_symbol (this is called flattening)? That is, do you represent x+(y+z) as +[x;y;z]? In this case, the extension rules may not be necessary.

So, here, I would expect rather something like this:
1) if there is an argument headed by z, then apply rule2, else go to 2)
2) if there is an argument headed by s, then go to 3), else fail
3) if there is another argument headed by s, then apply rule3, else try to apply rule1

Anyway, indeed AC matching is difficult. So I would rather suggest to first implement it without using decision trees.

**Comment by Gaspi** [comment]
> You also need to add the infinite set of rules max(s^k(x),x) --> s^k(x) for every k>=0.

For this reason people sometimes use max/+ (both AC) with the rule `max x (x+y) --> x + y.`

> Why do you say that matching starts by trying to match rule1? Decision trees usually say which rule to apply depending on the shape of arguments.

What I call "matching" is the run of the decision tree. The output of the "matching" is indeed which rule to apply (with what substitution). I'm giving the detail of this algorithm.

> It also depends on the internal representation you use for applications of AC symbols. Do you use a new private term constructor AC:ac_symbol -> term list -> term with the invariant that no term argument is headed by the same ac_symbol (this is called flattening)? That is, do you represent x+(y+z) as +[x;y;z]?

Yes, I do exactly that.

> In this case, the extension rules may not be necessary.

Without them, `max (S i) (max i (S j))` doesn't match `max (S n) (S m)` while it seems that it should.
There is no unifier to the matching problem
```
max[S i ; i ; S j] = max[S n ; S m]
```

> So, here, I would expect rather something like this:
> 
>     1. if there is an argument headed by z, then apply rule2, else go to 2)
> 
>     2. if there is an argument headed by s, then go to 3), else fail
> 
>     3. if there is another argument headed by s, then apply rule3, else try to apply rule1

As much as possible I'd like to apply the rules in the order of their declarations.
This means:
- making sure `rule1` doesn't apply before considering the following rules
- remembering that a `s`-headed symbol was already fetched when matching against `rule1` to not redo the work when matching against `rule3`

**Comment by fblanqui** [comment]
Le 19/07/2019 à 13:21, Gaspard Férey a écrit :
>
> As much as possible I'd like to apply the rules in the order of their 
> declarations.
> This means:
>
>   * making sure |rule1| doesn't apply before considering the following
>     rules
>
What's the point of using decision trees then?

**Comment by Gaspi** [comment]
> What's the point of using decision trees then?

The following item:

>     * remembering that a `s`-headed symbol was already fetched when matching against `rule1` to not redo the work when matching against `rule3`

**Comment by fblanqui** [comment]
But this item is not specific to decision trees, is it? With your spec, you could as well use a "naïve" matching algorithm without decision trees like the one of LP.

**Pull request closed without merging**
