### PR TITLE
Update syntax.bnf + make bnf

### LINKED ISSUE #260: syntax.bnf is not up to date
https://raw.githubusercontent.com/Deducteam/Dedukti/master/syntax.bnf is not up to date

### PR DESCRIPTION
**Pull request by amelieled**
This PR updates `make bnf` and the generation of the file `syntax.bnf`. (Fix #260 )

### CODE REVIEW

**Comment by amelieled** [comment]
Hi!
Is it possible to merge this PR?

**Comment by francoisthire** [comment]
I think it would be better if we can ensure it is consistent with https://github.com/Deducteam/Dedukti-standard . Is there something urgent relate to this MR?

**Comment by amelieled** [comment]
There is no emergency, but this updates the documentation now. Just do `make doc` to be in sync with the changes.

**Comment by fblanqui** [comment]
Updated in #332

**Pull request closed without merging**
