### PR TITLE
Create command #ASSERT and fix #CHECK behaviour

### PR DESCRIPTION
**Pull request by GuillaumeGen**

### CODE REVIEW

**Comment by rlepigre** [comment]
I suggest the following syntax change, although I think this is a good idea to distinguish between `#CHECK` and `#ASSERT`.

```
#CHECK t : A.
#CHECK NOT t : A.
#CHECK t == u.
#CHECK NOT t == u.
(; Same for #ASSERT ;)
```

In words, I propose two things:

- Allow for negation of a `#CHECK` or `#ASSERT`
- Replace convertibility check `#CONV t, u.` with the above (and also allow negation and `#ASSERT` on them).

**Comment by Gaspi** [comment]
I like Rodolphe suggestion better.
I'm simply afraid using the colon `:` as the separating token might be ambiguous since that character is likely to also occur in the surroundings terms.
I suggest either using double colon
```
#CHECK a :: A.
#CHECK a == b.
#CHECK #NOT a == b.
```
or use a prefix keyword
```
#CHECK #TYPE a, A.
#CHECK #CONV a, b.
#CHECK #NOT #CONV a, b.
```
Side notes:
- to avoid ambiguities the `NOT` keyword should also be prefixed with the command escaping character `#`. Indeed `NOT` could be a defined symbol in the signature.
- Should we also have a command `#CHECK t.` that simply checks the well-formedness of `t` ?

**Comment by rlepigre** [comment]
Why not use `#CHECKNOT` then?

For the `::`, I think that we would be fine with a simple `:` if the term is parsed at a low enough priority level (probably application level).

Also, we could use `=` instead of `==` since there is no `=` in the syntax. Right?

**Comment by rafoo** [comment]
I like your syntax propositions, especially the last ones by @rlepigre. Maybe we can also combine both checks using `#CHECK t = u : A` (but it is not clear what `#CHECKNOT` would mean in this case).

**Comment by GuillaumeGen** [comment]
The syntax of the PR right now is:
```
    #CHECK t1 == t2.     (;  display "YES" if t1 and t2 are convertible, "NO" otherwise. ;)
    #CHECK t1 :: t2.     (;  display "YES" if t1 has type t2, "NO" otherwise. ;)
    #CHECKNOT t1 == t2.  (;  display "YES" if t1 and t2 are not convertible, "YES" otherwise. ;)
    #CHECKNOT t1 :: t2.  (;  display "NO" if t1 does not have type t2, "YES" otherwise. ;)
    #ASSERT t1 :: t2.    (;  fail if t1 does not have type t2. ;)
    #ASSERT t1 == t2.    (;  fail if t1 is not convertible with t2. ;)
    #ASSERTNOT t1 :: t2. (;  fail if t1 does have type t2. ;)
    #ASSERTNOT t1 == t2. (;  fail if t1 is convertible with t2. ;)
```

**Comment by GuillaumeGen** [comment]
I agree with you Rodolphe, I made the required changes

**Comment by francoisthire** [comment]
Syntax remark: I don't like having two commands #CHECKNOT and #CHECK. I prefer using a modality in this case. I suggest something like:
```
#CHECK ! a == b
``` 

where the symbol `!` would be the modality.

By the way @rafoo  , you told me that you could avoid using the symbol `::` , but I don't see how. Have you any idea about this?

**Comment by francoisthire** [comment]
On this example, I don't like the behaviour of your commit

```
#NAME test.

nat : Type.

#CHECK (a : nat => nat) : nat -> Type.
```

The answer given is
```bash
NO
ERROR line:5 column:30 Unexpected token '->'.
```

Sure, you can use parenthesis to resolve the ambiguity. With `::` instead of `:`, you don't need parenthesis. What is the best here?

**Comment by GuillaumeGen** [comment]
Why use ':' but '==' ?
Furthermore, I think that the README should be more precise on the fact that we must put parenthesis around every term which is not only an identifier.
Is this behaviour really better than using '::' ?

**Comment by rafoo** [comment]
I have no opinion on the choice of '=='. The error message for unsolvable contraints uses "~~" for conversion.

**Comment by rlepigre** [comment]
Merged into PR #38 (will be merged into master at the same time).

**Pull request closed without merging**
