### PR TITLE
Use the Pp module for printing error messages

### PR DESCRIPTION
**Pull request by rafoo**
See the discussion in issue #45.

### CODE REVIEW

**Comment by francoisthire** [comment]
It's ok for me. Have you more improvement to do on this PR?

**Comment by rafoo** [comment]
Pretty-printing of error messages can still be improved but I do not have time for it. Here are two small improvements that I have in mind:

- Avoid cutting right after an open parenthesis.
- Reduce the indentation in messages of the form `Error while typing 't'`.

**Comment by francoisthire** [comment]
Can you merge this PR with the master branch?

**Comment by francoisthire** [comment]
It is a little bit outdated. This will be probably fixed in a future PR.

**Pull request closed without merging**
