### PR TITLE
Fixing the commands to compile libraries and add Cron job to the CI

### PR DESCRIPTION
**Pull request by GuillaumeGen**
This pull request tries to get back some CI running on the libraries.
I am not familiar with `nubo` yet, but it is probably better to use it rather than get old archives and sedding them to update the syntax.
By the time, I think that checking libraries remains useful.

### CODE REVIEW

**Comment by GuillaumeGen** [comment]
Cron job does not seem to be triggered from pull requests (quite expected to be honest), so one has to merge it to see if everything works as intended (I hope so, the syntax is simple and the command worked on my computer).

Furthermore, the part that has already been tested (setting up a working cache and testing a few libraries at each pull request) is worth a merge, no matter the quality of the untestable part.

**Comment by francoisthire** [comment]
> so one has to merge it to see if everything works as intended (I hope so, the syntax is simple and the command worked on my computer).

I would be very surprised if there is no other way. Unfortunately, my knowledge of GitHub Actions is quite poor and I cannot come up with a more constructive comment.

**Comment by GuillaumeGen** [comment]
Would be surprised too, but I do not know any better solution.

**Comment by GuillaumeGen** [comment]
This PR is 2 months old. What is its status now?

**Review by gabrielhdt — APPROVED** [review]

**Pull request merged**
