### PR TITLE
I don't understand what 'opam install dedukti' does

### PR DESCRIPTION
**Pull request by GuillaumeGen**

### CODE REVIEW

**Comment by rlepigre** [comment]
Is there a problem or not? :) https://youtu.be/Pr8ETbGz35Q

**Comment by GuillaumeGen** [comment]
I did understand that it install Dedukti. To be more precise, my questions are "Which version of Dedukti does it install ? Is it a good idea to put it in our .travis.yml ? Especially, when you look at the build log, it does not seem to compile the sources. And if it install a version of Dedukti which is does not correspond to the commit we are testing, why do we want to do it ?"

**Comment by rlepigre** [comment]
You are probably right. Let's merge!

**Comment by Gbury** [comment]
A small comment: I typically use `opam install` in my travis scripts (in at least one of the test paths) to check that opam installation is not bugged, but in thoses cases, a useful thing is to force a specific version to be installed, matching the pinned version (for instance "devel" seems to be used by dedukti), using `opam install dedukti.devel`.
This allows to check that a typical user can indeed install dedukti and that the install instructions for opam are not broken.

**Comment by rafoo** [comment]
Two remarks:
- opam does compile the sources but it redirects stdout and stderr to its own log files.
- In the travis script, Dedukti is pinned by the line `opam pin add --no-action dedukti .` so the only version that opam can install after this line corresponds to what is described in the `opam` file of the `master` branch.

**Comment by Gbury** [comment]
About the redirection and logs, using `OPAMVERBOSE=1` makes opam print to stdout/stderr all the commands (and errors) executed.

**Comment by fblanqui** [comment]
Please, document all this in say some README.travis.


Le 09/02/2018 à 12:20, Raphaël Cauderlier a écrit :

**Pull request merged**
