### PR TITLE
Polarization

### PR DESCRIPTION
**Pull request by gburel**
Integration of polarized deduction modulo into Dedukti.

Files without polarization should not be affected, except that their discrimination trees would be duplicated.

### CODE REVIEW

**Comment by francoisthire** [comment]
@Gaspi We should start a bench on this branch to check if we have lost something.

**Comment by francoisthire** [comment]
@gburel Is this feature still needed? I think that with #125 there could be another way to implement it this feature.

**Comment by gburel** [comment]
> @gburel Is this feature still needed? I think that with #125 there could be another way to implement it this feature.

I did not had time to work on it. It should probably better be added to lambdapi. It does not need to be in Dedukti's next release.

**Comment by francoisthire** [comment]
Too old, I close.

**Pull request closed without merging**
